"""Deployment of a generated architecture G_n on a reference SSI stack (Hyperledger Aries: ACA-Py agents, Indy ledger, tails
server, Postgres). What is deployed are the components and connectors of G_n, not the patterns (a pattern is a graph
transformation): every component v is realised in the agent of its role (the root of its containers: holder, issuer,
verifier), as the row of its type says; every connector by the row of its protocol (sheet 'Deployment (components)').
    deploy(G_n) = U_v delta(type(v)) on agent(role(v))  U  U_e delta(protocol(e)) on the agents of its ends
called by generate.py: result.json -> deploy/{docker-compose.yml, <role>.args, smoke_test.sh, DEPLOY.md}
An element the stack does not realise is reported, never dropped silently."""
import os, sys, json
HERE = os.path.dirname(os.path.abspath(__file__))

# Two profiles of the Aries stack: no-ledger (default, runnable at once) and indy (needs the von-network ledger built locally:
# git clone https://github.com/bcgov/von-network; ./manage build; ./manage start).
DEPLOY_PATH = os.path.join(HERE, "..", "..", "2_feature_model", "deployment.json")
REAL = json.load(open(DEPLOY_PATH, encoding="utf-8"))["realisation"]
IMAGE = "ghcr.io/openwallet-foundation/acapy-agent:py3.12-1.3-lts"
BASE = ["--admin 0.0.0.0 {admin}", "--admin-insecure-mode", "--inbound-transport http 0.0.0.0 {port}", "--outbound-transport http",
        "--endpoint http://{name}:{port}", "--label {name}", "--wallet-name {name}", "--wallet-key {name}-key", "--auto-provision",
        "--auto-accept-invites", "--auto-accept-requests", "--auto-respond-credential-offer", "--auto-store-credential", "--log-level info"]
ROLES = {"holder": (8020, 8021), "issuer": (8030, 8031), "verifier": (8040, 8041)}


def role_of(cid, comps):
    while comps[cid][1] is not None: cid = comps[cid][1]
    return cid.lower()


def provenance(steps):
    prov = {}
    for st in steps:
        for c in st.get("components_added", []): prov[c] = st["pattern"]
        for c in st.get("refines", {}): prov[c] = st["pattern"]
    return prov


def deploy(result_path, profile="no-ledger"):
    r = json.load(open(result_path, encoding="utf-8")); out = os.path.join(os.path.dirname(result_path), "deploy"); os.makedirs(out, exist_ok=True)
    comps = {k: tuple(v) for k, v in r["architecture"]["components"].items()}
    conns = [tuple(c) for c in r["architecture"]["connectors"]]
    prov = provenance(r.get("refinement", []))
    services, agent_args, tests, notes, unsupported, substituted = {}, {k: list(BASE) for k in ROLES}, [], [], [], []

    def apply(entry, label, agents):
        if entry is None: unsupported.append(f"{label} (no realisation in the knowledge base)"); return
        if not entry["realised"]: unsupported.append(f"{label}: {entry['note']}"); return
        parts = [entry] + ([entry["indy"]] if profile == "indy" else [])
        if profile != "indy" and entry["noledger_substitution"]: substituted.append(f"{label}: {entry['noledger_substitution']}")
        for part in parts:
            for sv in part.get("services", []): services[sv] = sv
            for a in agents:
                for o in part.get("options", []):
                    if o not in agent_args[a]: agent_args[a].append(o)
            for t in part.get("tests", []):
                if t not in tests: tests.append(t)
        notes.append(f"{label}: {entry['note']}")

    def target(entry, own):
        a = (entry or {}).get("agents", "")
        if a == "all": return list(ROLES)
        if a in ROLES: return [a]
        return [x for x in own if x in ROLES]

    for cid, (typ, _) in comps.items():
        e = REAL["components"].get(typ); role = role_of(cid, comps)
        tag = f" <- {prov[cid]}" if cid in prov else " (G0)"
        apply(e, f"{typ} [{role}]{tag}", target(e, [role]))
    seen = set()
    for src, dst, name, proto, payload in conns:
        e = REAL["connectors"].get(proto); ends = [role_of(src, comps), role_of(dst, comps)]
        key = (name, proto, tuple(ends))   # every connector of G_n is reported once
        if key in seen: continue
        seen.add(key)
        apply(e, f"{name} [{proto}] {ends[0]} -> {ends[1]}", target(e, ends))
    if profile != "indy":
        for k in ROLES: agent_args[k].append("--no-ledger")
    L = [f"# generated by deploy.py ({profile} profile) from " + os.path.basename(os.path.dirname(result_path)), "services:"]
    for name, image in services.items():
        if name == "tails-server": L += ["  tails-server:", "    image: bcgovimages/tails-server", "    command: tails-server --host 0.0.0.0 --port 6543 --storage-path /tmp/tails", "    ports: ['6543:6543']"]
        elif name == "postgres": L += ["  postgres:", "    image: postgres:15", "    environment: [POSTGRES_PASSWORD=wallet]", "    ports: ['5432:5432']"]
    for role, (port, admin) in ROLES.items():
        args = " ".join(a.format(name=role, port=port, admin=admin) for a in agent_args[role])
        L += [f"  {role}:", f"    image: {IMAGE}", f"    command: start {args}", f"    ports: ['{port}:{port}', '{admin}:{admin}']"]
        if "postgres" in services and role == "holder": L += ["    depends_on: [postgres]"]
        if profile == "indy": L += ["    extra_hosts: ['host.docker.internal:host-gateway']"]
    open(os.path.join(out, "docker-compose.yml"), "w", encoding="utf-8").write("\n".join(L) + "\n")
    for role in ROLES: open(os.path.join(out, f"{role}.args"), "w", encoding="utf-8").write("\n".join(a.format(name=role, port=ROLES[role][0], admin=ROLES[role][1]) for a in agent_args[role]) + "\n")
    T = ["#!/usr/bin/env bash", f"# smoke test ({profile} profile): exercises the requested functions on the deployed agents through the ACA-Py admin API", "set -e",
         "H=http://localhost:8021; I=http://localhost:8031; V=http://localhost:8041",
         "echo '1. agents up'; for a in $H $I $V; do curl -sf $a/status/ready >/dev/null && echo \"   $a ready\"; done",
         "echo '2. connection holder <-> issuer (DID Exchange, did:peer)'",
         "INV=$(curl -s -X POST \"$I/out-of-band/create-invitation?auto_accept=true\" -H 'Content-Type: application/json' -d '{\"handshake_protocols\":[\"https://didcomm.org/didexchange/1.1\"]}' | python3 -c 'import sys,json; print(json.dumps(json.load(sys.stdin)[\"invitation\"]))')",
         "curl -s -X POST \"$H/out-of-band/receive-invitation?auto_accept=true\" -H 'Content-Type: application/json' -d \"$INV\" >/dev/null; sleep 3",
         "curl -s $H/connections | python3 -c 'import sys,json; c=json.load(sys.stdin)[\"results\"]; print(\"   connections:\", [x[\"state\"] for x in c])'"]
    for i, t in enumerate(tests, 3): T.append(f"echo '{i}. {t}'   # admin API call to complete for the scenario")
    T.append("echo 'done'")
    open(os.path.join(out, "smoke_test.sh"), "w", encoding="utf-8").write("\n".join(T) + "\n")
    md = [f"# Deployment of the generated architecture (Aries stack, {profile} profile)", "",
          "Run: `docker compose config` (validity), `docker compose up -d`, then `bash smoke_test.sh` (agents up, one connection).",
          "Indy profile, diploma case: `python 12_play_diploma.py <this folder>` registers the public DIDs, starts the agents and plays issuance and presentation.",
          "Admin APIs with Swagger: holder http://localhost:8021/api/doc, issuer http://localhost:8031/api/doc, verifier http://localhost:8041/api/doc.", "",
          "Profiles: no-ledger (default, runnable at once) or Indy (`python 10_generate.py ... --indy`), after building the ledger:",
          "`git clone https://github.com/bcgov/von-network && cd von-network && ./manage build && ./manage start` (ledger console on http://localhost:9000).", "",
          "## Services", *[f"- {k}: {v}" for k, v in services.items()], *[f"- {role}: ACA-Py agent ({IMAGE}), ports {p[0]} / admin {p[1]}" for role, p in ROLES.items()], "",
          "## How each component and connector of the architecture is realised", *[f"- {n}" for n in notes], "",
          "## Substitutions in this profile", *([f"- {s_}" for s_ in substituted] or ["- none"]), "",
          "## Elements the stack does not realise (reported, not silently dropped)", *([f"- {u}" for u in unsupported] or ["- none"])]
    open(os.path.join(out, "DEPLOY.md"), "w", encoding="utf-8").write("\n".join(md) + "\n")
    print(f"deployment ({profile}) written to {out}: services {list(services)} + 3 agents; substituted: {len(substituted)}; unsupported: {unsupported or 'none'}")
    return out, unsupported

def main():
    deploy(sys.argv[1] if len(sys.argv) > 1 else "out_S1/result.json", sys.argv[2] if len(sys.argv) > 2 else "no-ledger")

if __name__ == "__main__":
    main()
