"""Deployment of a generated architecture on a reference SSI stack (Hyperledger Aries: ACA-Py agents, Indy ledger, tails
server, Postgres), so that the components exist as runnable services and the requested functions can be exercised.
called by generate.py: result.json -> deploy/{docker-compose.yml, <role>.args, smoke_test.sh, DEPLOY.md}
Each selected pattern maps to configuration of the stack; patterns the stack does not realise are reported, not dropped silently."""
import os, sys, json
HERE = os.path.dirname(os.path.abspath(__file__))

# pattern id -> what it becomes in the deployment: part C of the knowledge base, sheet "Deployment (Aries)".
# Two profiles of the Aries stack: no-ledger (default, runnable at once) and indy (needs the von-network ledger built locally:
# git clone https://github.com/bcgov/von-network; ./manage build; ./manage start).
import json
DEPLOY_PATH = os.path.join(HERE, "..", "..", "2_feature_model", "deployment.json")

def _load_mapping():
    """Part C of the knowledge base as written by 2_feature_model/build_rules.py (deployment.json)."""
    d = json.load(open(DEPLOY_PATH, encoding="utf-8"))["mapping"]; M = {}
    for p, r in d.items():
        if not r["realised"]: M[p] = None; continue
        m = {"note": r["note"], "services": {x: x for x in r["services"]}, "all": r["options"]["all"],
             "roles": {k: v for k, v in r["options"].items() if k != "all" and v}, "test": r["tests"]}
        ind = {"services": {x: x for x in r["indy"]["services"]}, "all": r["indy"]["options"]["all"],
               "roles": {k: v for k, v in r["indy"]["options"].items() if k != "all" and v}, "test": r["indy"]["tests"]}
        if ind["services"] or ind["all"] or ind["roles"] or ind["test"]: m["indy"] = ind
        if r["noledger_substitution"]: m["noledger"] = r["noledger_substitution"]
        M[p] = m
    return M

MAPPING = _load_mapping()
IMAGE = "ghcr.io/openwallet-foundation/acapy-agent:py3.12-1.3-lts"
BASE = ["--admin 0.0.0.0 {admin}", "--admin-insecure-mode", "--inbound-transport http 0.0.0.0 {port}", "--outbound-transport http",
        "--endpoint http://{name}:{port}", "--label {name}", "--wallet-name {name}", "--wallet-key {name}-key", "--auto-provision",
        "--auto-accept-invites", "--auto-accept-requests", "--auto-respond-credential-offer", "--auto-store-credential", "--log-level info"]
ROLES = {"holder": (8020, 8021), "issuer": (8030, 8031), "verifier": (8040, 8041)}

def deploy(result_path, profile="no-ledger"):
    r = json.load(open(result_path, encoding="utf-8")); out = os.path.join(os.path.dirname(result_path), "deploy"); os.makedirs(out, exist_ok=True)
    patterns = [p.split("_")[0] for p in r["selection"]]
    services, agent_args, tests, notes, unsupported, substituted = {}, {k: list(BASE) for k in ROLES}, [], [], [], []
    for p in patterns:
        m = MAPPING.get(p, "missing")
        if m is None: unsupported.append(p); continue
        if m == "missing": unsupported.append(p + " (no mapping yet)"); continue
        parts = [m] + ([m["indy"]] if profile == "indy" and "indy" in m else [])
        if profile != "indy" and "noledger" in m: substituted.append(f"{p}: {m['noledger']}")
        for part in parts:
            services.update(part.get("services", {}))
            for k in ROLES: agent_args[k] += part.get("all", []) + part.get("roles", {}).get(k, [])
            tests += part.get("test", [])
        notes.append(f"{p}: {m['note']}")
    if profile != "indy":
        for k in ROLES: agent_args[k].append("--no-ledger")
    L = [f"# generated by deploy.py ({profile} profile) from " + os.path.basename(os.path.dirname(result_path)), "services:"]
    for name, image in services.items():
        if name == "tails-server": L += ["  tails-server:", "    image: bcgovimages/tails-server", "    command: tails-server --host 0.0.0.0 --port 6543 --storage-path /tmp/tails", "    ports: ['6543:6543']"]
        elif name == "postgres": L += ["  postgres:", "    image: postgres:15", "    environment: [POSTGRES_PASSWORD=wallet]", "    ports: ['5432:5432']"]
    for role, (port, admin) in ROLES.items():
        args = " ".join(a.format(name=role, port=port, admin=admin) for a in agent_args[role])
        L += [f"  {role}:", f"    image: {IMAGE}", f"    command: start {args}", f"    ports: ['{port}:{port}', '{admin}:{admin}']"]
        if "postgres" in services and role == "holder": L += ["    depends_on: [postgres]"]
        if profile == "indy": L += ["    extra_hosts: ['host.docker.internal:host-gateway']"]
    open(os.path.join(out, "docker-compose.yml"), "w", encoding="utf-8").write("\n".join(L) + "\n")
    for role in ROLES: open(os.path.join(out, f"{role}.args"), "w", encoding="utf-8").write("\n".join(a.format(name=role, port=ROLES[role][0], admin=ROLES[role][1]) for a in agent_args[role]) + "\n")
    T = ["#!/usr/bin/env bash", f"# smoke test ({profile} profile): exercises the requested functions on the deployed agents through the ACA-Py admin API", "set -e",
         "H=http://localhost:8021; I=http://localhost:8031; V=http://localhost:8041",
         "echo '1. agents up'; for a in $H $I $V; do curl -sf $a/status/ready >/dev/null && echo \"   $a ready\"; done",
         "echo '2. connection holder <-> issuer (DID Exchange, did:peer)'",
         "INV=$(curl -s -X POST \"$I/out-of-band/create-invitation?auto_accept=true\" -H 'Content-Type: application/json' -d '{\"handshake_protocols\":[\"https://didcomm.org/didexchange/1.1\"]}' | python3 -c 'import sys,json; print(json.dumps(json.load(sys.stdin)[\"invitation\"]))')",
         "curl -s -X POST \"$H/out-of-band/receive-invitation?auto_accept=true\" -H 'Content-Type: application/json' -d \"$INV\" >/dev/null; sleep 3",
         "curl -s $H/connections | python3 -c 'import sys,json; c=json.load(sys.stdin)[\"results\"]; print(\"   connections:\", [x[\"state\"] for x in c])'"]
    for i, t in enumerate(tests, 3): T.append(f"echo '{i}. {t}'   # admin API call to complete for the scenario")
    T.append("echo 'done'")
    open(os.path.join(out, "smoke_test.sh"), "w", encoding="utf-8").write("\n".join(T) + "\n")
    md = [f"# Deployment of the generated architecture (Aries stack, {profile} profile)", "",
          "Run: `docker compose config` (validity), `docker compose up -d`, then `bash smoke_test.sh` (agents up, one connection).",
          "Indy profile, diploma case: `python 12_play_diploma.py <this folder>` registers the public DIDs, starts the agents and plays issuance and presentation.",
          "Admin APIs with Swagger: holder http://localhost:8021/api/doc, issuer http://localhost:8031/api/doc, verifier http://localhost:8041/api/doc.", "",
          "Profiles: no-ledger (default, runnable at once) or Indy (`python 10_generate.py ... --indy`), after building the ledger:",
          "`git clone https://github.com/bcgov/von-network && cd von-network && ./manage build && ./manage start` (ledger console on http://localhost:9000).", "",
          "## Services", *[f"- {k}: {v}" for k, v in services.items()], *[f"- {role}: ACA-Py agent ({IMAGE}), ports {p[0]} / admin {p[1]}" for role, p in ROLES.items()], "",
          "## What each selected pattern became", *[f"- {n}" for n in notes], "",
          "## Substitutions in this profile", *([f"- {s_}" for s_ in substituted] or ["- none"]), "",
          "## Patterns the stack does not realise (reported, not silently dropped)", *([f"- {u}" for u in unsupported] or ["- none"])]
    open(os.path.join(out, "DEPLOY.md"), "w", encoding="utf-8").write("\n".join(md) + "\n")
    print(f"deployment ({profile}) written to {out}: services {list(services)} + 3 agents; substituted: {len(substituted)}; unsupported: {unsupported or 'none'}")
    return out, unsupported

def main():
    deploy(sys.argv[1] if len(sys.argv) > 1 else "out_S1/result.json", sys.argv[2] if len(sys.argv) > 2 else "no-ledger")

if __name__ == "__main__":
    main()
